version: '3.9'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - .mongo/data/db:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 10
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - .docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - .docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  deploybl-server:
    build: .
    restart: always
    hostname: deploybl-server
    container_name: deploybl-server
    depends_on:
      - mongodb
      - rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deploy.rule=Host(`${DEPLOYBL_TREAFIK_HOST}`)"
    env_file:
      - .env
    volumes:
      - ./repos:$REPOSITORIES_PATH
      - ./event_logs:$EVENT_LOGS_PATH
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    networks:
      - web
      - default
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  web:
    external: true